name: leaderboard export

on: 
  push:
  schedule:
    - cron:  '* 0 * * *'

jobs:
  export_leaderboard:
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v2
