name: leaderboard export

on: 
  push:
  schedule:
    - cron:  '* 0 * * *'

jobs:
  export_leaderboard:
    container:
      image: nikolaik/python-nodejs:latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
